print(' ______________________________________')
print('/ Use the terminal to unleash the full \ \n')
print('\ power of your GNU/Linux system       /')
print(' --------------------------------------')
print('   \\n')
print('    \\n')
print('     \  .--.')
print('       |o_o |')
print('       |:_/ |')
print('      //   \ \\n')
print('     (|     | )')
print("    /'\_   _/`\'")
print('    \___)=(___/')